"use client";
import { AnimatePresence } from "framer-motion";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
        <body suppressHydrationWarning={true}>{children}</body>
      </AnimatePresence>
    </html>
  );
}
