"use client";
import { AnimatePresence } from "framer-motion";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
        <body className={inter.className}>{children}</body>
      </AnimatePresence>
    </html>
  );
}
