import './globals.css'

export const metadata = {
  title: "Almonds.",
  description: "Generated by create next app",
  icons: "../assets/images/almonds-svg.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
